### ISSUE TITLE
PR #7 breaks JavaScript compatibility

### ISSUE THREAD

**Issue by rradczewski** [jezen/is-thirteen#10]
I'm sorry, but running this on latest bleeding edge node v0.10 yields the following totally weird error I didn't read:

```
SyntaxError: Unexpected token ;
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
```

I'm not sure, but I'm guessing its [this line](https://github.com/jezen/is-thirteen/commit/aa7bea76cd49c10c21221f2000fc119459f3a5ad#diff-168726dbe96b3ce427e7fedce31bb0bcR2)...

**Comment by rradczewski** [comment]
+1 same error

**Comment by rradczewski** [comment]
+1 +1 +1 need this for my app

**Comment by jezen** [comment]
@rradczewski contacting the A-Team. Please hold.

**Comment by rradczewski** [comment]
+1 +1 +1 +1 +1 !!!!!!

**Comment by jezen** [comment]
@rradczewski Fixed in https://github.com/jezen/is-thirteen/commit/f5df1e9acfeb448808f3c3557058e427a6f5ef57 pleas review thamk you.

**Comment by rradczewski** [comment]
Sorry, took too long so I switched to angular, which has a similar function. Kthxbye
