### ISSUE TITLE
PHP version

### ISSUE THREAD

**Issue by df2** [jezen/is-thirteen#12]
Right now there is nothing like this available to the PHP community. Would you consider a PHP version so we can use it too? Thx

**Comment by rosswintle** [comment]
I had a stab at this: https://github.com/rosswintle/IsThirteen

Feel free to fork or contribute.

**Comment by sileence** [comment]
@rosswintle sadly that version does not implement SOLID principles in general and can't be mock since it is a static function.

**Comment by gytdau** [comment]
@sileence that's just PHP. Disgusting in general.

I guess that solves the problem.

**Comment by sileence** [comment]
@gytdau this was suppose to be a joke :)

**Comment by rosswintle** [comment]
@sileence `this` may well be a joke. But it depends on the scope. ;)

**Comment by gytdau** [comment]
@sileence that was also supposed to be a joke :(
