### ISSUE TITLE
Not enough jQuery

### ISSUE THREAD

**Issue by franciscop** [jezen/is-thirteen#16]
What if I wanted to use jQuery? Could this be converted into a plugin and be supported?

``` js
$.isThirteen(12); // false
$.isThirteen(13); // true
```

**Comment by yavorski** [comment]
This project is so exciting!

**Comment by jezen** [comment]
@franciscop i'm not sure if this is technically correct because i think you need to wrap the plugin invocation in lo-underscore for it to be babble compatible.

**Comment by Xiphe** [comment]
I'd rather not get to framework/library specific here. Obvious solution is to build a wrapper called `jquery-is-thirteen` that uses this lib as a dependency and exposes it as described above.

**Comment by franciscop** [comment]
Maybe a non-trivial case would be:

```js
$('input[name="number"]').isThirteen();
```

But that looks like real work and not just a joke (;

**Comment by Xiphe** [comment]
go for it!
