### ISSUE TITLE
Add a not equals 13 function

### ISSUE THREAD

**Issue by gytdau** [jezen/is-thirteen#19]
This makes my code look dirty:
`if(!isThirteen(x, true)) {`

I'm proposing a function called `isNotThirteen`. We would then have something like this instead:
`if(isNotThirteen(x, true)) {`

This is of the utmost importance for my SaaS startup.

**Comment by dietergoetelen** [comment]
I like this idea, we can even take this a step further and build something fluent:

```
import { is } from 'is-thirteen';

is(x).thirteen()
is(x).not.thirteen()
```

What do you guys think?

**Comment by gytdau** [comment]
This is a great idea.

And then we can also solve issue #20 like so:
```js
is(x).roughly.thirteen()
is(x).within(3).of.thirteen()
```

**Comment by jezen** [comment]
@dietergoetelen if u implement then i merge because API look so beautiful

![crying-roy](https://cloud.githubusercontent.com/assets/1926747/14014376/6473ddf0-f1b2-11e5-8145-0a88183f6521.gif)
