### ISSUE TITLE
unmaintained?

### ISSUE THREAD

**Issue by shime** [jezen/is-thirteen#199]
is this still maintained? seems like it needs a new maintainer, there are too much open issues yo.

**Comment by sassoo** [comment]
+1

**Comment by sassoo** [comment]
+1

**Comment by sassoo** [comment]
+1

**Comment by cyphar** [comment]
:+1: :shipit:

**Comment by jaywunder** [comment]
+10

**Comment by cubbK** [comment]
+13

**Comment by Almenon** [comment]
I just got added in as a maintainer! Thanks @jezen.

I've been going through some of the PR's..... but there is a lot of them. Might take me a couple years 😄
