### ISSUE TITLE
Add a roughly equals 13 function

### ISSUE THREAD

**Issue by gytdau** [jezen/is-thirteen#20]
A function that would check if a number is kind of _close enough_ to 13. We could have this as a separate parameter in the main function. `true` checks for _exactly_ 13, and `false` checks for _about_ 13.

```js
isThirteen(13, false, true) // true
isThirteen(13, false, false) // true
isThirteen(12.99, false, true) // false
isThirteen(12.99, false, false) // true
```

**Comment by jjanssen** [comment]
I would suggest making a different method for this. Like `roughlyThirteen`, it would become easier to test!

**Comment by gytdau** [comment]
@jjanssen if we're going with the proposed syntax in #19 then the new syntax would be:

```js
is(12.5).roughly.thirteen() // true
is(12.5).not.roughly.thirteen() // false
```

**Comment by jjanssen** [comment]
@gytdau awesome! Looking forward to its release!
