### ISSUE TITLE
lower case roman numerals shouldn't be accepted

### ISSUE THREAD

**Issue by fabiofidanza** [jezen/is-thirteen#202]

**Comment by frg** [comment]
Not according to the highly reliable website wiktionary.com! https://en.wiktionary.org/wiki/Appendix:Roman_numerals

> Roman numerals are essentially known as uppercase letters: I, V, X, L, C, D and M. However, it is possible to use lowercase letters.

**Comment by lukaseder** [comment]
Wrong. Proof:

1. Open up MS Word
2. Create an ordered list
3. Nest list three levels deep
4. Observe; 
![image](https://cloud.githubusercontent.com/assets/734593/14076691/7ec5c6c0-f4e4-11e5-9554-2b523d105d98.png)

**Comment by fabiofidanza** [comment]
Closing, thanks for your comments.
That must be a "modern" addition, I've never seen any lowercase roman numeral in Rome, on Roman era stone engravings.
