### ISSUE TITLE
Is.not.thirteen out of scope, reduce feature creep

### ISSUE THREAD

**Issue by joshlongerbeam** [jezen/is-thirteen#304]
I see the draw of wanting to type more English-like-code via
`is('something').not.thirteen();`
instead of
`!is('something').thirteen();`

But this needs to be more modular. Perhaps
`var isnt = require('is-not-thirteen');`
`isnt('something else').thirteen();`
?

**Comment by tavianator** [comment]
I don't think `isnt('something else').thirteen()` reads correctly in English, isn't that right?

**Comment by suBDavis** [comment]
There's some ambiguity.  
For example:
Isn't '13' thirteen?  Well of course it bloody is.

So really `isnt('something else').thirteen()` has the same function as `is()`

The same argument could be made about `is().not.thirteen()` 
i.e. "Is 'somethign' not thirteen?" would illicit the response "Yeah, sure is!"
