### ISSUE TITLE
-13 not workn

### ISSUE THREAD

**Issue by timseverien** [jezen/is-thirteen#31]
please fix

**Comment by timseverien** [comment]
Whoa this is issue #31

**Comment by jaroel** [comment]
Cannot reproduce, plz supply failing test

**Comment by timseverien** [comment]
you didn’t even try why don’t you tried?1@ why do you hate me? dont yo uwant to fix?

**Comment by nicolas-besnard** [comment]
Please, can you fix this ?

**Comment by jaroel** [comment]
there's already a baker's dozen in queue. plz hold.

**Comment by gytdau** [comment]
-13 != 13

I guess we could implement another function, `is(x).kind.of.thirteen()`?

**Comment by jaroel** [comment]
I think we need PFN (pulp fiction notation).
`does(x).look.like.a.thirteen()?`

**Comment by Xiphe** [comment]
please do not overload this lib. Instead create `is-minus-thirteen` and publish to npm

**Comment by barryp** [comment]
-13 isn't just "kind of" 13, it's the complete opposite. It's like anti-13, if the two ever came into contact they'd completely annihilate each other!  It's like evil mirror-universe 13.  Think 13 with a goatee and a knife tucked into its sash.

  `would(x).take.your.dilithium()`

**Comment by stelcheck** [comment]
```javascript
try {
  does(it).look.like.a.thirteen()
} catch (bullet) {
  leg.putInto(bullet) // leg being our log collection framework
}
```
