### ISSUE TITLE
Too many issues

### ISSUE THREAD

**Issue by gytdau** [jezen/is-thirteen#385]
how do we even get 84 issues?

**Comment by antonioJASR** [comment]
I know @gytdau , it should be thirteen.

**Comment by macdja38** [comment]
I agree, I'm very glad we have an issue about this.

**Comment by Elronnd** [comment]
@jezen can you close issues until we only have 13?

**Comment by alexsmbaratti** [comment]
I am from one year in the future. We're at 100 now.

**Comment by Almenon** [comment]
hmmm.... If I close 3 issues I can make the number of issues 169, whose square root is 13, thus restoring balance to the universe.  I'll start off with this one :P
