### ISSUE TITLE
Not an issue, but a feature request

### ISSUE THREAD

**Issue by KevOBrien** [jezen/is-thirteen#429]
Could you add functionality to check if something is 428 (four hundred and twenty eight)?

Thanks.

**Comment by miyu** [comment]
Pointless feature creep. I don't want a library that checks for 10, 285, or even 428. I just need a library that checks if a number if 13, and nothing more.

**Comment by oriadam** [comment]
Already supported - this should do the trick:
`is(428).plus(1).divideby(33).thirteen()`

**Comment by gytdau** [comment]
As @oriadam mentioned above, it would be sacrilegious and against our code of conduct to check against additional numbers.
