### ISSUE TITLE
"Access Denied" is not 13!

### ISSUE THREAD

**Issue by disjunction** [jezen/is-thirteen#430]
this returns "Access Denied" but is assumed as 13
https://scontent.cdninstagram.com/hphotos-xtf1/t51.2885-15/s320x320/e35/12237511_444845689040315_1101385461_n.jpg

see test: https://github.com/jezen/is-thirteen/blob/master/test.js#L14

(maybe relates to #224 ?)

**Comment by disjunction** [comment]
sorry - is a duplicate of #428

**Comment by denysvitali** [comment]
@disjunction You may need to change the title. This repo only checks if something is equals to 13.  
I can say for sure that 6,227,020,800 is not 13.
