### ISSUE TITLE
Again!

### ISSUE THREAD

**Issue by daison12006013** [jezen/is-thirteen#461]
Here we go again, it's been atleast a year since then, and we're on top of the trending! F*CK THAT 💯 💯 💯 💯 💯 💯 💯

**Comment by takahiro-saeki** [comment]
@daison12006013 I was wondering why this project is so popular and many people are sending PR and making issues. haha

**Comment by daison12006013** [comment]
@takahiro-saeki, Because validation "13" is awesome! It makes useful when you don't need to re-invent the wheel 😅
