### ISSUE TITLE
code seems wrong

### ISSUE THREAD

**Issue by tkkcc** [jezen/is-thirteen#504]
`canSpell` in `is.js`
```
        canSpell: {
          thirteen: function(){
            return x.toLowerCase().includes("t","h","i","r","t","e","e","n");
          }
        },
```
[includes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes)

**Comment by eraleis** [comment]
I made a pull request: https://github.com/jezen/is-thirteen/pull/515
