### ISSUE TITLE
"on üç" is not italian

### ISSUE THREAD

**Issue by Jefffrey** [jezen/is-thirteen#520]
On line: https://github.com/jezen/is-thirteen/blob/master/test.js#L88 you say that that is Italian. I've been Italian for all my life (25 years) and I can tell you that I've never seen 13 written like that in Italian and [Google Translate seems to agree with me](https://translate.google.com/#auto/en/on%20%C3%BC%C3%A7).

**Comment by Sweenu** [comment]
it's Turkish to be exact :)

**Comment by banminkyoz** [comment]
Fixed, Can close now

**Comment by gytdau** [comment]
#431 closed, thanks!
