### ISSUE TITLE
why use this repo

### ISSUE THREAD

**Issue by extJo** [jezen/is-thirteen#570]
..?

**Comment by dev-juyoung** [comment]
I wonder...

**Comment by PlayMa256** [comment]
Come on... life is too serious to take everything seriously... joke around some time.

**Comment by lazarljubenovic** [comment]
It's good for forward compatibility in case they deprecate the current mathematical postulates.

**Comment by miyu** [comment]
We use it in our node.js-powered elevator firmware to skip floor 13.

**Comment by extJo** [comment]
thanks :)

**Comment by methewhenmeth3** [comment]
this is very late but this pisses me off. you use this repo if you need to know if a number is thirteen, silly.
