### ISSUE TITLE
Rewrite it in Rust?

### ISSUE THREAD

**Issue by malios** [jezen/is-thirteen#582]

**Comment by SRGOM** [comment]
rust isn't powerful like JavaScript, mkay?

**Comment by 5hanth** [comment]
@malios https://crates.io/crates/is_thirteen_rs

**Comment by 5hanth** [comment]
@jezen this issue can be closed as I have initiated a [rust implementation here](https://github.com/5hanth/is_thirteen_rs)

**Comment by gytdau** [comment]
@5hanth oh my god why.

**Comment by Almenon** [comment]
Good job @5hanth ! Closing.
