### ISSUE TITLE
please bundle with webpack

### ISSUE THREAD

**Issue by Xananax** [jezen/is-thirteen#624]
Webpack allows for automated code splitting. So if for example I had a 26 and I wanted to compare it twice, Webpack would split it. Even numbers as large as 52, for example, would not be a problem.

Webpack also provides:

1 - dead code removal
2 - bundling of css and even using pre-processors3
3 - web assembly (very important to make is-thirteen fast)
2 -  bundling of everything
6 - even more bundling

Webpack can even be used with typescript, so it would solve https://github.com/jezen/is-thirteen/issues/521, https://github.com/jezen/is-thirteen/issues/53, and https://github.com/jezen/is-thirteen/issues/404, and in all likelihood all the issues

**Comment by Almenon** [comment]
Webpack only has 7 letters, closing.
