### ISSUE TITLE
number of issues is not divisible by 13

### ISSUE THREAD

**Issue by Almenon** [jezen/is-thirteen#640]
I accidentily closed too many issues, resulting in 168. There should be 169 issues!

> 13 * 13 = 169

**Comment by Almenon** [comment]
Closing - issues is now fixed.

**Comment by Almenon** [comment]
oh wait, damnit. That created the issue again. Reopening.

**Comment by pandermatt** [comment]
There are now 170 issues, I think we can now close this issue
