### ISSUE TITLE
Clearly lacking a delegate overload

### ISSUE THREAD

**Issue by wwwlicious** [jezen/is-thirteen#65]
I feel this library clearly lacks the ability to pass in a delegate. instead of :-

`is(13).thirteen(); // true`

let's have some 

`is(() => { return 13; }).thirteen(); // true`
`is((i) => { return (i - i) + 13; }).thirteen(); // true`

**Comment by Xiphe** [comment]
yeah, would have been really helpful here: https://github.com/Xiphe/gulp-is-thirteen

right now i need to hack around that using `{}.toString = (i) => 13;`
