### ISSUE TITLE
Who is using is-thirteen?

### ISSUE THREAD

**Issue by danielcaldas** [jezen/is-thirteen#657]
It would be nice to have in the README.md a section with the companies that are currently using `is-thirteen` in production?

**Comment by streamich** [comment]
![image](https://user-images.githubusercontent.com/9773803/55179234-4fa29280-5187-11e9-98db-5a2de83588a0.png)

**Comment by r6203** [comment]
May god save those brave souls

**Comment by 2999** [comment]
they're using it, see 'Dependents' tab on this page: https://www.npmjs.com/package/is-thirteen

**Comment by danielcaldas** [comment]
Now we know, some good transparency 😄 

![image](https://user-images.githubusercontent.com/11733994/58338380-0baad180-7e48-11e9-81c8-e4c31f3a3676.png)
