### ISSUE TITLE
Create constant for 13 instead of having "magic numbers"

### ISSUE THREAD

**Issue by haggy** [jezen/is-thirteen#66]
The number `13` is sprayed many places around the lib. I suggest that you create a constant aptly named `THIRTEEN` just in case one of the following scenarios occur:

- The number `13` changes
- What math currently is becomes something else when machines take over
- Something, something quantum mechanics

**Comment by aeharding** [comment]
+1, this could make switching to 12 easier in the future.

There seems to be a growing consensus by developers that 12 is the new best practice for comparing if it is thirteen.

**Comment by gytdau** [comment]
@aeharding so I see now that the opinion of one person has become a 'growing consensus'? Blasphemy this is.

**Comment by aeharding** [comment]
[Hey hey hey I have a source](https://medium.com/@aeharding/twelve-is-the-new-thirteen-e415748db5b7#.9rvsroenw)

**Comment by haggy** [comment]
We have further proof that `12` is the new `13`

http://12isthenew13.com/

**Comment by apollocatlin** [comment]
I disagree with everything seen here. You should all be ashamed of yourselves. 13 is 13. How does noone here get it?

**Comment by gytdau** [comment]
You spent $10 on that. Good work.

**Comment by aeharding** [comment]
@apollocatlin The web moves quickly and you must be using the latest and greatest or you aren't cool.

**Comment by apollocatlin** [comment]
Don't try telling me 14 is the new 13. 13 will ALWAYS be valuable.

**Comment by haggy** [comment]
@gytdau It was $12.27 with tax. Premium.

**Comment by apollocatlin** [comment]
@haggy 24/7 phone support?

**Comment by haggy** [comment]
@apollocatlin It's 12/13 phone support currently.

**Comment by aeharding** [comment]
@haggy $12.27, you say? coincidence???

**Comment by haggy** [comment]
@aeharding I think not!

**Comment by gytdau** [comment]
@jezen we are being overthrown. Send backups.

**Comment by jezen** [comment]
Freidns please i know programming is like fashion its in one year out the other but comparing with thirteen is serious business and we are a serious project

**Comment by aeharding** [comment]
Hey we never established what base 13 with in. If it was in base 4 but it was meant to be in base 5, the number should actually be 12!

**Comment by haggy** [comment]
@jezen Plus, `12` is a valuable number in quantum theory suggesting that it holds the secrets to time travel.

**Comment by haggy** [comment]
@jezen We now have a lib to help with numbers that are __NOT__ thirteen.

https://www.npmjs.com/package/is-not-thirteen

FYI @aeharding there's a nice function in there for all of us on the `12` side :smile:

**Comment by gytdau** [comment]
Fixed by #326
