### ISSUE TITLE
Please change the number. 13 is the dead number (PT)

### ISSUE THREAD

**Issue by stanleygomes** [jezen/is-thirteen#660]
@thiagohenriquef brought me here.

github.com/thiagohenriquef

In Brazil, 13 is the dead, murder, threat and the worst things number. Please change it to any other.

Thanks.

**Comment by rafael1995** [comment]
Lula free!

**Comment by rafael1995** [comment]
In Brazil, 13 is work and Progress! 

Lula free!

**Comment by thiagohenriquef** [comment]
@rafael1995 YOU'RE A COMMUNIST! GO BACK TO CUBA!!!

@stanleygomes you're right, the number should be changed to 666, the number of the beast

**Comment by stanleygomes** [comment]
Change to 666 now

**Comment by stanleygomes** [comment]
put the cookie down now.
