### ISSUE TITLE
I AM THE REAL AUTHOR

### ISSUE THREAD

**Issue by monlouisj** [jezen/is-thirteen#673]
It's funny how you took advantage of me not going open-source fast enough. I started working on a lib named "is-13" 3 years ago and now, you just pop up with the same idea, and oh, the same code! How strange is that ?!

**Comment by jezen** [comment]
The real author is the friends we made along the way

**Comment by monlouisj** [comment]
It's been a wonderful journey! I guess it's time to close this issue.
