### ISSUE TITLE
Add Z̸͇̟͔̭͉̽͛̈̇͑̍͌̓́͌̆̌͐̿̌̍̊̏̄̉͌̓̍͌͘̕͠͠ā̷ͅl̸̬̠̩̘̰̲͙̰̯̙͉͕̓͌̑͒̀́̔͛̽̿̃͂̈́̓̃̍̃̈́̓̑̓̾̐̓͗̔͐̓̆͐̒̊̈̅͋̀̽̚̚̕̕̕͜͜͝͝͠ͅǧ̷̨̢̨̩̥̖͈͚͇̮̗͔͈͍̱̣̫͖̟̱̰̺̤̳̱̳͇̠͇̯̜͜͝ǫ̵̛̛̘̜̜͙͕͖͙̰͎̞̺̙̺̮̹̫̳̳̟͓̜̜̱̰͇̾͊̈́͗́̑̂͊̐͑͋̒͗͒̕͝ ̶̡̧̛̯͈̟̘͕͓͖̰̼̣̮̳̠̙̟̹̞̲̲̩̲̝͉̣̜̝̲͙̻̹̘̥̰̗͎̌̔̏̾̔̂̽̊̄̓̈̃̓̏̇̍̿́͊̔͂̇̈̋̄͆̀̊̿̍̂̌̍̊̕͜͝͝ͅT̶̨͈̭̯͇̻̱͈͚̳̅́͘ě̵̢̦̓͗̈́͆͂͊͊̎̐̊͂͗͊̈́̇̽̉́̐́͘̚̚͠͠x̴̨̡̛̛̬͈̰͇͔̺̯͚̥̻͇̲̱͖̦̗̗͇͇̳̗͙̳̩̭̥͍͔̭̯̤̦̦͍̺͙̜̟̮̗͔͛̒̏͐̑̎͑̐͑̈́̅͛́͌̑͒̋̈́͛̒͒̾͛̎̈́̔͐̈́͋̋͊̈́͗̆͘̚͝͝ͅͅţ̴͕̪͇͚͍͈͔̪̹̫̲̗͇̣̩̫̈̌̑͂́́̊̕͜͜͜ͅ support

### ISSUE THREAD

**Issue by Ryan-McPartlan** [jezen/is-thirteen#722]
When the new Gods consume the old, all that is known will become unknown and all that has gone will come again. In order to future proof is-13 against this eventuality, we should support recognition for the L̸̢̡̨̨̧̢̡̢̨̧̨̢̡̧̧̨̧̛̛̛̳̟̳̬͓̥̖̣̩̠̺̟̮̟̦̥̰̯̜̤̖͈͚̘͕̮͔͎͙̖̞̯͚̬͉̖̦̳̙͍͍͈͖͕̝͔̤̬̭̭̻͈̻̩̹̦̦͈͍̰͎̙̖͉͇̤̞̱͉͙͉̜̰̣̭̳͚̻̩̲̦̭̹̗͎̣͓̞̭̯̹̳̲͇̜̰̜̫̰̤̮̫̝̼̥͎͚͍͖͚̹̪̣̲̬̼͈͈̜̮͖̭̫͇̯͍͎̫͇̳͓͕̻͇̬̣͚̠͈̣̟̖͓͚̹̟̫̝̤̞̺̲̯͚̫̞̬͎̦͖̮̖̯̬̽͊͒̎̔̀͌̅̾̆̄͊̉̓̈͗̇͊͐͂̃̾̈́͛̏͊̉͆̋̀̅͗̀͛̈͑̂͗͑̿̂̎͋̎͛͗̄̓͐͊̑̌̃̽͒̉̀̄̿͆̾̋̎̑͑̽͌̍̅͛͂͗̆͛͋̋̏͗͒̃̾̂͗̾̃̔̑̓̈́̊̈́̄́̌̀̈́͒̅̉́̂͗͛̾̍̈̄̈̀̂̉́͆̂̒́̀̅̈̑̓̈́́́̎̓͛̈̐̓͌̈́͛̽̊̈́̄͑̅͒̊͒͛̑̇̌͆̇͌̾̊́̋̉͒̍̂͋̆̓̽̇̔̽̾̈̌̐̏̃͌̏̓͒̇̂́͂̋̀̇̂̈́̋̊͂͛̇͐͊̿̅͘͘̕͘̚͘̚̚͘̚͘͘͜͜͜͜͜͠͝͝͝͝͝͠ͅͅͅǫ̸̧̨̨̡̨̨̢̨̨̨̡̢̛̛̛̛̖̭̫̩̟̹̤̝͇̠̪͍̣̫͉̘̺͖̩͍̣̹̦͓̬̥̙̻̝̯̰̭̼̭̮̰̖͕̖̮̦̺͎̠̬͇͓̻̲̞̻̥̫͈͔̗̤̙̖̩̥̗̖͎̞̙̪͙̳̘̮͓̠̻̞͉̭̳̙̝̟̼̲̳͍̫̮͍̟͍̜͙̗͇̥͈̻̻̠͙͕̦̘̻̳̭̭̜̼͓͖̠̲̳̓̒̒̐̂͋͐̏̆͋̋̎͋̈́͐̈́͆̋̐͋̔̇͒͗̌͑́͛̃͆̃̆̆̎̈͌̈́̿͌́̑̎̀̈͌͂̄̎̈̇̌͗̈̔̔̀͊͒͊̉̂̌͗̽̓̒͑̍̀͑̇̓͌̔̿̿̑͐̈́͆͒̽͋͆̂͐̀͂̾͋͌̀́̑̈́̓̀́͑͒̽́̽̈́́̈́̄̃͆͌̓̊̈͗́̌̅̆̽̃̓̏͐̈͗̋̎́́̿̐̋̊̋̏̔͋̐̑́̓̄̈́̋͑̂̌̉͑̓̽́̌̂̓͗̋͆͗͆̇̇͗́̾͌̉͛̈̌̔̔̐̓̈́̐̃̑́̓͂̂͛̎̄̾̾̆͐̀̆̇̒̋̑̾̋͑͗̋͗̐̌̓̿̇̓͆͌̂̆̉͑̀̏̉̀̈́͌̈́̎̒̋́̎͂̿̿̋̈́̽͘͘̚̕͘̚͘͘̚̚̕͘̕̕̕̕̚̕̚͘͘͘̚̚͜͜͜͜͠͝͝͠͝͝͠͝͝͝͠͝͠͝͝͠͠͝͝͠͝͝ͅͅͅͅͅŕ̴̡̢̨̧̢̡̨̨̨̨̢̡̧̛̛̛̛̛̛̛̘̦̮̗̣̲̪̹̙̟͖̰̻̰͖̙͉̗͔͍̥͈̺̬̳͖̟͚͔̯͚͙̖̳̠͉̭͍̪̦͓̞̰̦̳̳̖̭̝̪͍̲̲̜̫̦̖̭͇͍̮̗̯͇̠̭̳͕͎͙͕̫͙̠̺̻̘͖̪̪͍̖̤̥̟̦̹̣͖͕̥̬̼̬̪͇͔̼̲͎̟͍͓̗̦̹̠͇̮̖͙̙̻̭̼̣̗̥̖̗̙͖͕̪̼̜͙̩̫̻̯͍̯͎̩͙̞̫̭̟̦͇͗̔̏͌̿́̉͑̂̓́̅̃̎̽̆͌̄̔̉̒̊̐̆̆̄́̅́͗̒͊̀̽̐͊̒̅̒́͑̍̈͊̊͌̆̐̎̔͑̑́̽͋̍͆̀̌͊̏̑́͋̈̌̈́̊͊̂̋̊͐̔̀̆̃͌̎̄̍̾͆͑̓̿̾̋͋̐̔̃͐̐̿͑́̅̄̀͑̔̎̾̏̿̂̆̍̃̏͗́̉̽̾͌̑͊͗̂̇̆̅͌͒̒͂̃͐̀̆́̆̑̈̃́̿͆͊̎̿͆̈́̓͐̐̇̂̑̉͌̈́͆̄͗͋̒̓̈́͗̀͑̏̒͑͑͒̿̑̂̊̍̋͆̌́̓́̽̓͌́̒̇̐̅̑̾̿͐̇̓̍̓͆͌͌̄̽͋̃̉̕̕̚͘̚̚̕̚̚̚͘͜͜͜͜͜͝͝͠͠͝͝͝͠͠͝͝͝͝͠͝͝͠ͅͅͅd̸̡̢̨̨̧̢̢̧̢̨̨̨̡̛̛̛̛̛̮̲̥̣̩͍̤̥͇͇͎͍̩̭̖̖̺͖̤͕̭̦͉͔͚͉͚̳͙͈̲͚̥͙̞̯̤̭͉̰͙͚̙̰̤̻̲͍͖̫̗̱͇̠̲̼̙̲͇̰͖̙̝̥͓̮̹͙̫̦̞̭͔͉͓̥̝̭̠̻̞͇̞̗̥̱͈̤̤͔̲̞͔͍̞̯̼͇̳͍̤̜̦̤̩̲̰͈̫͉̱̰̜̙̥͕̪͍͎̯̮̹̻̫̤̤͎̱͎̦͍̐̋́̿̿̃̒̅̑̄̾̀̑̐̿̀̆̑̊̋̔̉̈́̆͛̆̿̽̀́̋͆̅͐̐̂̄͛͂͋̈́͋̆̎̽̀͒̓̿̅͛̑̈́͋͋̈́͗̓̊̂͛̈́̾͂̐͑̂̇͂̅̏͐͒͋̔̔͊̄͊͐̔̑̀͐͑̉̓̃̈́͐̊̋͐́̉̆̔̈́́̇̆̓͛̈́̓͒̿̅̐͂͂̅̒̀̍̈́͂͂̀̉̌́̓͑͊̀̿̒͋̏͒̔́̈́͊̒̐̊̔̓̍̀̃̓̑͗̔͒̔̃̀͋̐̈̐̋̃͛͆͛̏̓̂͆̋͗͒̋͌̌̐͌̆͋̾̆̀͌̓̊̔̽̃͛̈́̍̾́͋̓̔̇̔́̏̅͌̀̄̉̋̅̀́̔͒͛̇͛̌̔͐̆̅̆͌̋̾̌͋̈́͌̇̊̓͊̒͐̒͘͘̕̕̚̕͘̕͘͘̕̕̕͘̕̚̕̕̕̚͜͜͜͠͠͝͝͝͝͝͝͠͝͝͝͝͝͝͝ͅͅͅͅͅͅͅͅs̴̨̡̡̧̧̧̢̢̨̨̨̢̨̢̧̧̛̛̛̛̛̛̩̰̦͓̹͈̥̖̬̯͎̪̪̱͇͖͍̗̪̦̝̯͔̘̟̝̠̰̪̩̩̙̮̺̜͇̭̙͎̲̥̗͙̝̞͎̘̩͈̞̺̥̖̻̫̠̰̱̦͈͖͚̫̥̲̳̣̝̮̘̭͚̹̥͔̞̪̪̠̖̲͚̺̗̹̦̤̯̣̩͚̬͚̻͚̱̦̰͉̦͖̟̼̘̤͍̦͎̱̰̝͈͓̞̹͇͚̦̣̳̺̫͖̦̲̰̭̳̼̖̤̪̲͓̙͍̜̪̞̺̠̫̝̯̹͖̬̮͍̼̳̻̱̞̣̟̱̦̠̺̩̩̘̭̳̦͇̣̠̦̭̟̝̀͌̎͑̒̔͐̽́̀̃͂̑͆̏͂́̽̔̽̔̍͌̓̐͛͑́̋̄͐͂̅͑̏̓̓̀͑̓́͊̂́̇̈̃̀̅̈̄͗̽͑̍̐̾͌͊̅̾̓̉͌͌̄̎̏͒́͌̓́̈́͌͌̏̓̐̎́́̂̌̋̐̏́̒̃̋͛̈͆̒̾̈́̎̈́̈́̈͗̔͌̑̍̉̍̎̈́͂͛̃́̎͆͛̈́̒͌̾́͛̊͘̕̕̕̕̚͘̚͜͜͜͜͜͝͝͠͠͝͝͝͝ͅͅͅͅͅ ̸̨̨̡̨̡̢̢̨̡̢̧̨̧̨͚̳̯̱͉̙͈̤̖̩̹̙̘̠̤̻̹̥͈̹̗̻̣̤̘̳͇̻̜͎̞̞͈̯̘̳͇͚͉̰͍͚̜͖͚̳͓̙̗͍̰̯̖̹͕͉̹̝̗͍͍̮͉̯̪̞̩̤͚̳̱̞̤̫̪͙̝̞͖̱̞̩̞̖̪͓͇̯̠̣̠̜̪̫͖͚̙̰͇̥̯͎͍̖̥̤̥̩͉͎̘͙͖͙̥͙̙̰͔͉̰̱̥͇͇̣͇̪͙̝̳̞̺̥͍̪͔̩͚͕̼̟̤̪͙͚͖̳̹̜͍̱͖̦͈̣̻̞̘̮̤̥̝̳̜͍̹͌͜͜͜͜ͅͅͅͅͅc̷̢̛̛͍͓̘̞̗̮̙̮̠̙͑̑̈́̿̑͋̈́́̒͐̍̏̃͑͆̐̈́͑͋̃͆̏̀̍̆͆͋͒̅͆͂̈́̅̅̓̃̈́̓́̅͛̔͑͑̈́͂͗͑̀͑͂̑͑̂̇̈́̇̌̅́͋̌̽̂̍́͊̉̉̓̈͐̑͛͋̑̾͆̑̍̂̒̄͂͆̕̚̕̚͘͝͝͠͝͠͝͝͝͝ͅy̶̡̛̛͕̤͖͎͕͇̏͗̀̉̃̈́͂̌̂̿̈́̽͗͌̌͆̆̊̈́̀̓͋̇͋͊̓̒̓̈̔̾͐̿̈́̒̒̓̋̽̓̓̂̽̀̏̊̀̈́̔́͗̍̎̈́͂̇̒̎̓̽̓̍̒̋͊͒̌̋̅́̾̔͐̀̈́̈́̌̽̃̑̂̿̔̄̉͛̾̍͐̒̆̇̇̄͐͆̔̃͊̄͌͛̂̊̂͆̔̋̌̏͛́͆͗̍̽͒̍̈́̑̏͗̌̌̄͛̀̿͑͗̓̊̀̔̽̆̌͌̅͑̀̒̿̑̽͗̂́͒̔̑̾̌̆̚̕͘̚̚̕̕̕͘̕͘͘̕͘͘̕̕̕̚͘͝͝͝͠͝͠͝͠͝͝͝͠p̵̡̧̨̨̛̛̛̛̣͈̼̦͕̼̰͉͎̟͚͇͇̻͔̲̦̘͇̜͉̟̤̟͉̀̓̃̈́́͑͛̈̅̀̋͆̈́͌͆̉̔̊̈̇̃̐̓̐̎̈́͐̈̇͒̓̃̅͌͌͆̐̄̀͊͑́̀̿̄̊̒̌̅̀̑̾͐̓̿̐̔̀͂̎̂͗̈́͐̒̌͛͆͗̀̀͆̀͊̐̄̄͛̀͑̽̇̓̑̍̈́̑͛͗̀̿̐̈́̊͌̒̑̈́͗̎̈́̇͐͆̑͑̄̊̃̒̍̐̽̏͊̌̾̽̍̊̅̔͗̓͗̏͒́͒̌̄̀͐̉́͆̅͆͛̈́̄̌̾͒͆̉̓͑̿͛̉͋̐̔̑̓͌̔̿̀͛̐̐̉͆̔́̅́͆͆́́̾̅̍̋́͊̔̋͑̏̂̆̏̕͘̚̕͘̚̚͘̚͘̕̚̚̚͘̕̚͜͜͠͝͠͝͠͝͝͝͝͝͠͝͝͝͠͝ḩ̶̧̡̢̧̧̨̧̧̢̨̡̢̡̛̛͖̮̖̤͔̹̟͇̮̱͖̝̙̤̰͔͈̼̫̲̪̣̼̬̯̲͍͈͚̗͉̳̞̳̳̞̭̤͍̭̲̫̬̖̼̣͖͔̤͔̻̩̲̳͙̭͇̭͉͚̻̯͉̭̺̭̦͍͍͓̼̰̩̻͚̳̳̠̺̞̟͇͇̮̜̳̱͙̙̰̝̱̫̩̥̠̭̣͙̞͕̞̮̙̹̳͍̜͇̹̤̼̳͇͓͉͍͕̟̜̤͎̯̲̙̳̪̜̗͙̥̣̩̺͉͚͇͈̹̪̖̭̪̮͌͂̒̓̄̆̒̂̾́̂̔̀̒̀̈̊̋̒͛̐̌͆͛̍͆͂̎̓̒͌̔̀̄̂̈́̈́͒̀̽͌́̐͊̈́̅̀̓͗̅̀̇̍̈́͑̍̽͗̈͂͊̒̏͐̈́̇͛͐́̓͊̃͋̄̾̊͊̈́̈́̄͐͌̎̌̈́̑̅̈́͒̀͑͌͋̽͗͒̓̇̈́̂̂̂̍͐̌̔̐̄̇̑́̂̃͒̆̄͒̒̒̎́̔̿̄͑͆̏̈́̄̆͐͑̀̋̃̽͑̔͗͆̇̈̎̅̎̈́̐̔̄͑̐͑̈́̌̿͊͐̊̀͋̄͆̅̅̍̎̀͂͊̐́̓̈͋̆̓̎̇̓̈́̈́̓͑̈́̀́̀͌̿̃͒̂͋͛͗̅͑́͛̈́̇̀̋̌̎́̓̊̈́̌̆͊̋͒̓̀͋̄̔̅̎̈́͛̈͐̆͑͘̕͘̚͘͘͘͘̕̚̚̚͘͜͜͜͜͠͠͝͝͠͝͠͠͝͝͝͝͝͝͝͝͝͝͝ͅͅͅē̶̢̨̨̡̢̨̢̢̢̡̡̨̡̛̜͕̣̥͈̗͍̤̯̬͖͇̳̖̪̘͇̩͉͙̤̰͔̫̪̠̼͇̱̤̘͕̼̱͈̺̟͔͔̺̤̻͍̳͚̱͎͚̟̻̫̗̰͇̫̞̹̭̥̭͔̹̱̤̦̱͍̺͇̻̝͚͈͕͕͚͔̳̤̰̮̺͎̹̖̟̣͔̪̪̘͓̺̼̟̮̟̱̬͉̭̮̰͕̯̖͎͎̪̦͙͓͖̘͉̜̗͙̼̝̲̲͖͉̣̻͓͕͕͕̬̗̪͕̣͍͔͍̱̖͚͖̻̖̤͚̣̲̯̝̝̳̼̱̖̥̥̬̪̞͇̞͎̳͓͓̭̩̦͍̩̙̇͐̀͋͊͆̄͑̃̑́͜͜͜͜͠͝ͅͅͅͅŗ̷̢̡̨̭͔̮̟͎̺̙̥̝̭͎̙̙̤̣͉̹͇̺͕̱̫̪͎̤͈͖̺͍͔̥̭̭͚͔̫͔̺̰̺̳̣̱̤̠̹̪̺̮͇̜̤͉̣̺̼͇̣͓̞̱͚͉̬͓͚͕̖͈̖̗̰̬͓̲͇̖͔̮̞̠̜̩̓͗̈́̎̒̉͒͒̀̆̈́͐͋̋̏̊̿̅̈̿͆͋̉̍́̏̓͆͋̀̾́́͌͘͜͝͝͝ͅͅͅͅͅ. After the coming, I strongly suspect 13 will be the only number remaining, and that identifying it will be an even higher priority. 

It may also be worth having a meeting with management to determine how this oversight in requirements was allowed to occur. It's possible that they have yet to bear witness to the truth, which we should rectify immediately.

May you all find your peace in this noble work.

**Comment by Almenon** [comment]
I met with C̶̡̢̡̢̛̛͇͙̫̩̞̖͔͈̣̮̝̤̙̩͓̩̖̗̖̣͚̙̻̙͕̻̫̠̻͕̖̫͚͈̙̰̠̝̙͕̬̤̙̘̘̤̖̝͕̞̦̺̼̳̜͇̥͍̙̺̘̠̀̍̍̈́́̽̈́̀̑̏̽́̅͋̀̌̒͑́̌̎͗̒̆̆̒̏̀̐̎̽́̏̒̽̆̀͂̔̇̅̽̍͂̀͗͋̌͐͋̽̊̈́̃́̉͂͒͌͒́̽̾̑̍͌̓͊̈́̂͘̕͘̚͘̚̚͜͜͝͝͝͝h̶̛̲̖̺͎̗̞̹̉̒͆̀̈́̀̇̈́̈́̌́͌̍̑̈́́̓̐̑̂̆͛̈̓̒̎͋̑͑̐͊̓̾̉̾̽̍͋͆͊̓̋̀͐̓̐́̄̾͌̒̀̒̉̂͐̆͊̉̇̇̃͐͛̂̊̔̀̆̉͆̆́̑̑̆̐̓͆̍͆̑̇̄̀͊͒̅̉̋͘̚͘̚̚̚̕̕̚͝͝͝͝͝͝͝ͅư̵̧̛̲̭̰͕̮͕͍̟̺̝̪͖̝̝̞͓̫͕̽́̀͊̔͗̐̀̃̿̀̋̊̄̀́͐̒̂̒̀̈́̓̊̿͌̿̿̐̉͋́̇̓̄̍͊̄̐͗̍̚̚͝͝͠ṯ̷̢̧̡̡̛̘̝̭̜͈̜̠̹̠͙̦̦̻̱̜̘̩̩͉͓͚͔̭̭͖̞͍̗̣̥͇̟͙̥͚͍̬̝͉͖̲̫̝͙̖͋̌̓͂̓̒̈̈́̐͒͌͑̆̿͗̆̀̂͑̃̒͑̋̽̃̈̊́̄͘͜͜͜͝͠ͅḩ̶̧̧̢̨̛̛͎̺͚̰̜͙͖͕̣̙͔̹̲͎̺̞̝̰̖̺͚̭͙̘̯͎̜̦͙̞͈̹͕̖͈̫̯̱̙͔̰͔̜̺̤̩͌̓́͊͛͒̏͆͒̀́̅̈́̉͆͋̈͒̒̈́̑̽͆̒̀͌́̾̍͋̓̑̆̀̈́̈͗͌̃̉̏͌̎̂̐̈̑̈́͒̾̚̚͘͘͘͘̚͜͜͜͜͠͠͝ͅͅự̸̧̧̧̢̪̫͕̗̮͓̠̯̳̙̱̱̞̻͎̣̝̪͎̘̲͔̖̥̗̮̪̥̺̤̟̱̪͖̫̖̩͕̫̹͉̒͂̒͐̄̽̔̅̉̑̉̀̏͑͆̄̿̀̄͑̾͑̃̇͊͑͌͗̇̏̑̈͊̈̃͛̆́̂̃̈́̅̋̊̒͑̽̉̂̐́̈̑̓̀͂̐̋͗̄̉͋̈́̉̀͌͊̂́͊̍̇͊̅̆̽̂̓̎̔̋͊̈́̓͑͋̊̈́͐́̑͛͑̔̈̍̀̌̂́̏̎̾͆́̑̚͘̕̚̚̕͘͜͜͝͠͝͝͝͝͠͝ͅͅͅl̵̛̛̯̞͚͕̜̪͉͛͐͌̐͛̋̉͋̎͋̄̇͛̏̏̐̽̌̅̓̓͋͑́̆́͊̀̽̅̽̉͂̔̐̄̈̑͆͐͂́͛̏̑̃̋̑͊̿̾͐̉̾͋͋̋̔̅̋̑̄̓̓̽͆͒̃̐̍̄̂̒̾̃̌̀̒́̀̀̅̓͂͘͘͘͘̚̕͝͝͝͝͝͠͝͝ư̸̡͕̗͈̠͔̣͙̟͇̜͚͚͉͚͍͖̪̙̙̞͖͉̣̥̱̟̺̠̦͔̓͗̈́̔̂̽̊̅̀̒͂̎̃̊̇͜͜ͅ in our weekly one-on-one and we agree, zalgo support is needed. 

I have implemented it with https://github.com/jezen/is-thirteen/commit/732e4fbe0b85b982a7b33f26cd64c2bb28f33830 🎉

**Comment by ledlamp** [comment]
wow dang nice zalgo
