### ISSUE TITLE
but why 13

### ISSUE THREAD

**Issue by JingBh** [jezen/is-thirteen#742]
I must say that this is a really useful library, but I wonder why this is not about any number else, but 13?

**Comment by Almenon** [comment]
13 is a lucky number, a happy number, _and_ a star number. 

I'm not kidding, it is literally a happy lucky star number.

https://en.wikipedia.org/wiki/Happy_number
https://en.wikipedia.org/wiki/Star_number
https://en.wikipedia.org/wiki/Lucky_number

**Comment by JingBh** [comment]
@Almenon oh that makes sense... didn't think that way

**Comment by Rudxain** [comment]
> 13 is a lucky prime, a happy number, _and_ a star number.
> 
> I'm not kidding, it is literally a happy lucky star number.

Also a Pisano/Fibonacci number, which is a subset of the Lucas numbers
