### ISSUE TITLE
Create a Technical Steering Committee

### ISSUE THREAD

**Issue by aeharding** [jezen/is-thirteen#76]
In light of pull request #74, we should have a steering committee to discuss agenda items related to `is-thirteen`

We should take minutes every month or so as needed.

I think we should follow the Node conventions in how they transformed their project to have a committee.

https://nodejs.org/en/foundation/tsc/minutes/

We have 8 more seats available for those interested.
# Members
1. @aeharding
2. @gytdau 
3. @jezen
4. @stephenpoole
5. _your name here_

**Comment by gytdau** [comment]
I obviously automatically take a seat. Should this be held in the Gitter channels?

**Comment by aeharding** [comment]
@gytdau Yeah. I'll take notes on google docs

**Comment by jezen** [comment]
This is good i will bring biscuits

**Comment by gytdau** [comment]
Bring chocolate ones @jezen. And I swear to god if they have raisins I'm resigning.

**Comment by jezen** [comment]
I have made first commit of technical steering

![steering](https://s-media-cache-ak0.pinimg.com/originals/1b/3f/e3/1b3fe346a48149bc309b92036a20a277.gif)

**Comment by stephenpoole** [comment]
Hi, I'm that contributor that submitted a 5 line PR and now feel entitled to have strong opinions about the direction of this project. Naturally, I feel that I am the ideal candidate for this committee.

**Comment by aeharding** [comment]
@stephenpoole Added!

**Comment by stephenpoole** [comment]
@aeharding Great, so what about 14?

**Comment by jezen** [comment]
@stephenpoole 

![](http://www.frugaltravelguy.com/wp-content/uploads/2015/06/denied.jpg)

**Comment by aeharding** [comment]
Arbitrarily denied? Hey look, we are a committee!

**Comment by stephenpoole** [comment]
@jezen I see you attached an image that reads 'denied'. I have similarily attached an image that instead reads what I would like it to say.

![screen shot 2016-03-24 at 4 41 58 pm 2](https://cloud.githubusercontent.com/assets/3344159/14030756/a80fb6f6-f1df-11e5-8a1c-f6ab4245000c.jpg)

I feel we've really made progress here.

**Comment by stephenpoole** [comment]
I can see a case for 12, I guess, but I think 14 is the future.

**Comment by dideler** [comment]
I would like to make a case for why I am the next technician steering committee member.

When I was 13 my teacher asked me what I want to be when I'm older. I said
> I want to be important... I want to be a committee member!

To which she replied
> Make up your mind Dennis and choose one

So I went with committee member and have never looked back.

This is the perfect opportunity. I can't help with the steering, but I can help Make America Great Again.

I'm counting you all and counting on you all to make the right decision.

**Comment by dideler** [comment]
I am working on renewing my expired driver's license so I can help with steering.

**Comment by OceanOSdev** [comment]
If there's still room for another member, I'd be happy to join this committee.

**Comment by anknetau** [comment]
I present my candidacy to join this committee. I offer:

1. I will bring chocolate cookies to the meetings
1. I will oppose any 12s or 14s or any other degenerate 13s, **including the dreaded 12.9999999... recurring**.
1. will even shower every other meeting, _whether I need to or not._

A vote for me is a vote for **13**!

**Comment by mohnjatthews** [comment]
I too would like to join, however I have absolutely nothing to offer. No skills whatsoever. But I'll happily stand around, be the front man, and take all the credit. 

You can call me Mr Jobs.

**Comment by MattCordell** [comment]
I'd like to nominate myself. I've contributed nothing and unlikely to join any meetings/calls, and if I do I will stay on mute.

**Comment by world** [comment]
I believe because of my superior git username and my position as pure leech to the community I will be a perfect fit for a highly opinionated but unmotivated member of your committee. @world for the win! Hello?

**Comment by world** [comment]
Is I really hate this project as I find its scope way to wide and there are too many contributors with different agendas. If you take me on I will consitently vote each month to close source this thing in order to improve quality and increase revenue. Thank you for considering my application.

**Comment by world** [comment]
I meant PS not Is. See I'm perfect.

**Comment by macdja38** [comment]
I just found out about this project about 2 minutes ago but it already solves exactly 1 of my problems that I didn't even know was a problem. I think I'd bring a fresh outside perspective to the board and be able to bring what people outside the project think and see of the project into the committee were we can discuss it from all angles.

**Comment by harshilsharma63** [comment]
I should be on this committee because I brush my teeth twice a day.

**Comment by BusbyActual** [comment]
I would like to be a member of the technical community to discuss agendas. I feel I'm especially qualified as my favorite number is 13.

**Comment by jaacko-torus** [comment]
Why is this still open? We need to finalize this! My sister depends on it, and she's 13

**Comment by Almenon** [comment]
@jaacko-torus good point. Maybe we should create a committee to discuss finalizing the committee?

**Comment by dideler** [comment]
With the overwhelming submissions and wildly different ideas, we've ended up in a state of analysis paralysis. We clearly need a council to bring order. The council will handle the larger matters and the committees will sort out the details. I nominate myself as the first ~master~ member to sit on the council.

**Comment by BusbyActual** [comment]
And then there were the 13 best committee members

**Comment by anknetau** [comment]
I strongly suggest we bring in some high-rank military advisors to help us cut cost and focus the technical steering committee's energy towards an outcome

**Comment by Almenon** [comment]
We have a problem. The meeting naturally needs to happen on day 13 but there's only 7 days in a week :O

**Comment by tj-commits** [comment]
Please bring this back! I will join
