### ISSUE TITLE
"Portuguese" is spelled incorrectly in line 55 of test.js

### ISSUE THREAD

**Issue by ric2b** [jezen/is-thirteen#88]
I find incorrect comments to be very poor quality software artisanship and will not be using this module to compare against the number thirteen.

**Comment by jezen** [comment]
@ric2b Thamk you for your concern we have now correctly spelled Portugeese in PR https://github.com/jezen/is-thirteen/pull/80

**Comment by jezen** [comment]
@ric2b oh  no is wrong file what is Portugeese for OH NO

**Comment by ric2b** [comment]
This interaction further confirms my suspicion that you are sub-par programmers.
This module isn't even web scale or responsive. I think I'll home brew my own is-thirteen checker, based on MongoDB, like real programmers.
