### ISSUE TITLE
Russian "тринадцать" double-checking

### ISSUE THREAD

**Issue by voytovichs** [jezen/is-thirteen#91]
There are two "тринадцать" checks: line 41 and duplicate on line 73 in "index.js" file

**Comment by jezen** [comment]
@voytovichs yes becaus that means we are 200% sure that 13 in Russin is equal to 13 <sub>in russin</sub>

will not fix good day sir.

**Comment by voytovichs** [comment]
Such a smart move

**Comment by SahAssar** [comment]
I'd recommend that this be closed since it is fixed twice.

**Comment by Xiphe** [comment]
i heard you guys came up with this during closed beta. Man that must have been a rough time.
